# Debug Code Predictor indexing
import torch
from qwen_tts import Qwen3TTSModel

print("Loading model...")
model = Qwen3TTSModel.from_pretrained(
    "./model_0.6b",
    device_map="cpu",
    torch_dtype=torch.float32,
)

code_predictor = model.model.talker.code_predictor

print("\n=== Understanding the indexing ===")
print(f"Number of embeddings: {len(code_predictor.model.codec_embedding)}")
print(f"Number of lm_heads: {len(code_predictor.lm_head)}")

# From forward source:
# - Decode: inputs_embeds = self.model.get_input_embeddings()[generation_steps - 1](input_ids)
# - Logits: logits = self.lm_head[generation_steps](hidden_states)

# So for generation_steps = N:
# - Embedding used: embeddings[N-1]
# - LM head used: lm_heads[N]

# Valid generation_steps range:
# - embeddings[N-1] needs N-1 in [0, 14] → N in [1, 15]
# - lm_heads[N] needs N in [0, 14]
# - Combined: N in [1, 14]

# But wait, the original test with gen_steps=1 worked!
# And gen_steps=15 would need lm_heads[15] which doesn't exist

print("\n=== Testing generation_steps indexing ===")

test_input = torch.randint(0, 2048, (1, 5))

with torch.no_grad():
    # Test gen_steps = 0 (prefill-like)
    try:
        output = code_predictor(input_ids=test_input, generation_steps=0)
        print(f"gen_steps=0: OK, output shape {output.logits.shape}")
    except Exception as e:
        print(f"gen_steps=0: FAILED - {e}")

    # Test gen_steps = 1-14
    for gs in range(1, 15):
        try:
            output = code_predictor(input_ids=test_input, generation_steps=gs)
            print(f"gen_steps={gs}: OK, uses embed[{gs-1}], head[{gs}]")
        except Exception as e:
            print(f"gen_steps={gs}: FAILED - {e}")

print("\n=== What does lm_heads[0] predict? ===")
# If gen_steps starts at 1, lm_heads[0] would need gen_steps=0
# But gen_steps=0 uses embed[-1] which wraps around!

# Let me check if gen_steps=0 is used in prefill
# For prefill: generation_steps = inputs_embeds.shape[1] - 2
# If inputs_embeds has shape [B, 2, hidden]:
#   generation_steps = 2 - 2 = 0
#   This uses lm_heads[0]!

# So prefill with 2 tokens uses lm_heads[0]
# Prefill with 3+ tokens uses lm_heads[1+]

print("\n=== Prefill test with 2 tokens ===")
with torch.no_grad():
    # Create inputs_embeds with shape [B, 2, hidden]
    inputs_embeds = torch.randn(1, 2, 1024)
    try:
        output = code_predictor(inputs_embeds=inputs_embeds)
        print(f"Prefill (2 tokens): OK, gen_steps={output.generation_steps}")
        print(f"Output logits shape: {output.logits.shape}")
    except Exception as e:
        print(f"Prefill (2 tokens): FAILED - {e}")

print("\n=== Correct wrapper flow ===")
# Based on above analysis:
# - Prefill with [hidden, codebook0]: gen_steps=0 → lm_heads[0] → predicts codebook 1
# - Decode gen_steps=1: embed[0](codebook1) → lm_heads[1] → predicts codebook 2
# - Decode gen_steps=14: embed[13](codebook14) → lm_heads[14] → predicts codebook 15

# Wait, that's wrong. Let me trace more carefully.
# In decode mode, input_ids are the PREVIOUS codebook's tokens
# gen_steps=1: embed[0] embeds input_ids (which should be codebook 0 tokens)
# Then lm_heads[1] predicts codebook 1? Or 2?

# Actually from the forward, after decode:
# generation_steps += 1
# So gen_steps=1 becomes gen_steps=2 for the next step

# Let me trace the full autoregressive flow:
# 1. Prefill: inputs_embeds = [hidden, codebook0_embed], gen_steps = 0
#    → lm_heads[0] predicts codebook 1
# 2. Decode: input_ids = codebook1_tokens, gen_steps = 1
#    → embed[0] embeds... wait, embed[0] is for codebook 0, not codebook 1!

# The indexing is confusing. Let me just print what each embedding/head is for.

print("\n=== Embedding/Head correspondence ===")
# Based on the generation flow:
# - LM generates codebook 0
# - Code predictor predicts codebooks 1-15 (15 predictions)
# - embeddings[0-14] condition on codebooks 0-14
# - lm_heads[0-14] predict codebooks 1-15

# So:
# - embeddings[N] embeds codebook N tokens
# - lm_heads[N] predicts codebook N+1 tokens

# The original forward with gen_steps=N:
# - embed[N-1] embeds input_ids (codebook N-1 tokens)
# - lm_heads[N] predicts codebook N tokens

# So to predict codebook 1:
# - Need gen_steps=1
# - Uses embed[0] (embeds codebook 0 tokens) and lm_heads[1]
# Wait, that means lm_heads[1] predicts codebook 1, not lm_heads[0]!

# Let me verify:
# gen_steps=1: predict codebook 1 using lm_heads[1]
# gen_steps=2: predict codebook 2 using lm_heads[2]
# ...
# gen_steps=14: predict codebook 14 using lm_heads[14]

# What about codebook 15?
# gen_steps=15: predict codebook 15 using lm_heads[15] - OUT OF BOUNDS!

# And lm_heads[0]?
# gen_steps=0: predict codebook 0 using lm_heads[0]
# But codebook 0 is already generated by the main LM!

# I think lm_heads[0] is for prefill mode where gen_steps=0
# This is calculated as inputs_embeds.shape[1] - 2 = 0 when inputs_embeds has 2 tokens

print("Hypothesis:")
print("- gen_steps=0 (prefill with 2 tokens): lm_heads[0] predicts codebook 1")
print("- gen_steps=1: embed[0] + lm_heads[1] predicts codebook 2")
print("- gen_steps=14: embed[13] + lm_heads[14] predicts codebook 15")
print("Total predictions: codebooks 1-15 (15 predictions)")

print("\n=== Final understanding ===")
# Let me re-read the forward code:
# logits = self.lm_head[generation_steps](hidden_states)

# And the return:
# return Qwen3TTSTalkerCodePredictorOutputWithPast(
#     ...
#     generation_steps=generation_steps + 1,
# )

# So after each step, generation_steps increments
# If we start at gen_steps=0 (prefill with 2 tokens):
# - Step 0: lm_heads[0] → returns gen_steps=1
# - Step 1: lm_heads[1] → returns gen_steps=2
# - ...
# - Step 14: lm_heads[14] → returns gen_steps=15

# So the model supports 15 iterations total (gen_steps 0-14)
# Each iteration predicts one codebook:
# - gen_steps=0 → codebook 1
# - gen_steps=1 → codebook 2
# - ...
# - gen_steps=14 → codebook 15

# The confusion was about what gen_steps represents:
# gen_steps = output_codebook - 1

print("Corrected understanding:")
print("- gen_steps=N uses lm_heads[N] to predict codebook N+1")
print("- gen_steps=0 → codebook 1")
print("- gen_steps=14 → codebook 15")
print("- Total: 15 predictions (codebooks 1-15)")
