[project]
name = "camplusplus_coreml"
version = "0.1.0"
requires-python = "==3.11.13"
dependencies = [
    "torch",
    "torchaudio",
    "soundfile",
    "coremltools",
    "numpy",
    "requests",
]
